org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.daemon=false

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.1
loom_version=1.14.10
fabric_api_version=0.141.6+1.21.11

mod_version=1.0.0
maven_group=com.puuz
archives_base_name=puuz-map-shield
